### ISSUE TITLE
Cross compilation to Windows broken

### ISSUE THREAD

**Issue by Jake-Shadle** [rust-lang/stacker#58]
PR https://github.com/rust-lang/stacker/pull/57 broke cross compilation to Windows since it returned to the behavior that assumes that the MSVC toolchain, in particular ml64, is available and can be used.

I can submit a fix for this, would it be ok to add a CI step that tests that cross compilation from Linux works and that the tests run under wine?

**Comment by nagisa** [comment]
Sorry, `ml` is required for i686-pc-windows-msvc to work at all. This is a much more important use-case I feel and the cross-compilation functionality was breaking rustc (https://github.com/rust-lang/rust/pull/87680).

Since we have a test for [what rustc needs now](https://github.com/rust-lang/stacker/blob/9aa6cd28413c6984f7ab5e4c5a3981f418dfabf4/.github/workflows/test.yml#L49-L77), I'm happy to accept improvements that add cross-compilation support again in a way that does not break the rustc use-case.
